var hoodNames = [
  "Allston",
  "Back Bay",
  "Bay Village",
  "Beacon Hill",
  "Brighton",
  "Charlestown",
  "Chinatown",
  "Leather District",
  "Dorchester",
  "Downtown",
  "East Boston",
  "Fenway/Kenmore",
  "Fenway",
  "Kenmore Square",
  "Hyde Park",
  "Jamaica Plain",
  "Mattapan",
  "North End",
  "Roslindale",
  "Roxbury",
  "South Boston",
  "South End",
  "West End",
  "West Roxbury",
  "Fort Point",
  "Seaport",
  "Waterfront",
  "Mission Hill",
  "Longwood",
  "Central Square",
  "Harvard Square",
  "Cambridgeport",
  "Area 4",
  "Inman Square",
  "Kendall Square",
  "Porter Square",
  "Davis Square",
  "Winter Hill"
];

var cityNames = [
  "Boston",
  "Cambridge",
  "Somerville",
  "Brookline",
  "Chelsea",
  "Revere",
  "Quincy",
  "Watertown",
  "Medford",
  "Malden",
  "Everett"
];